version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: project
    ports:
      - 5432:5432


  app:
    build: ./
    container_name: java_app
    ports:
      - 8080:8080

