
server:
  port: 9120

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/project
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/changeset/changelog-master.yaml
    enabled: true