insert into message (message, name, person_id)
values ('message1', 'ivan', '1'),
       ('message2', 'ivan', '1'),
       ('message3', 'ivan', '1'),
       ('message4', 'ivan', '1'),
       ('message5', 'ivan', '1'),
       ('message6', 'ivan', '1'),
       ('message7', 'ivan', '1'),
       ('message8', 'ivan', '1'),
       ('message9', 'ivan', '1'),
       ('message10', 'ivan', '1'),
       ('message11', 'ivan', '1'),
       ('message12', 'ivan', '1'),
       ('message13', 'ivan', '1'),
       ('message14', 'ivan', '1'),
       ('message15', 'ivan', '1'),
       ('message16', 'ivan', '1'),
       ('message17', 'ivan', '1'),
       ('message18', 'ivan', '1'),
       ('message19', 'ivan', '1'),
       ('message20', 'ivan', '1');